### ISSUE TITLE
Fix shutdown of MPI comms between libE calls

### ISSUE THREAD

**Issue by jlnav** [Libensemble/libensemble#387] opened 2020-03-10 21:42 UTC
Based on #373 

See #385 for an example test.

Details will go below.

Edit as necessary.

**Comment by shuds13** [comment] 2020-03-10 23:23
We may need to ensure communications are closed out before leaving libE routine for mpi4py. This would mean requiring a return signal to the STOP is received by the manager. This should be the default, though could have the option to disable.

**Comment by shuds13** [comment] 2020-03-12 23:22
Following discussions regarding send/receive order of mesages.

My suggestion is that we always create a new duplicate of the communicator when we go into libE. And, when we exit libE, we free that communicator.

We might want to make the default for the manager to poll all active workers for either a calc return or NULL signal anyway before exiting. The worker will only return the NULL if it has received a STOP and has no data to return for an outstanding calc. This does not guarantee that other worker-to-manager messages have all been received (ie. logger message / libE_stat lines), as we cant know whats in the network. These messages should not be a problem for future libE calls, but they could be unexpected for other code sharing the communicator. However, freeing the communicator (always a libE-only communicator) should ensure no such contension.

I don't think there is a reason why we should have to use the supplied communicator and not a duplicate.

**Comment by jmlarson1** [comment] 2020-03-12 23:34
> I don't think there is a reason why we should have to use the supplied communicator and not a duplicate.

Sounds like the perfect solution, provided duplicating a comm preserves everything we need.

I also think it's good to poll all workers before exiting. If any are unresponsive, then we exit. Since we are using a duplicate communicator, no latent communication can cause an issue.

**Closed** 2020-03-20 17:01 UTC
Labels: Experimental, bug, enhancement
