### ISSUE TITLE
Extend testing across communication modes.

### ISSUE THREAD

**Issue by shuds13** [Libensemble/libensemble#408] opened 2020-03-26 03:55 UTC
Tests that are NOT run on all 3 comms types and are not obviously mpi-only etc...

I ran locally with 2 workers each run, including in a travis docker container.
The lines show the current TESTSUITE_COMMS.

passed all 3: mine and travis docker
- test_aposmm_one_residual_at_a_time.py:# TESTSUITE_COMMS: mpi
- test_persistent_fd_param_finder.py:# TESTSUITE_COMMS: mpi
- test_aposmm_pounders.py:# TESTSUITE_COMMS: mpi
- test_persistent_tasmanian.py:# TESTSUITE_COMMS: local

local passed - no tcp due to multiple libe calls:
- test_sim_dirs.py:# TESTSUITE_COMMS: mpi
- test_uniform_sampling_one_residual_at_a_time.py:# TESTSUITE_COMMS: mpi
- test_fast_alloc.py:# TESTSUITE_COMMS: mpi local
- test_aposmm_with_gradients.py:# TESTSUITE_COMMS: mpi [*hangs - no tcp check]
- test_persistent_aposmm_periodic.py:# TESTSUITE_COMMS: local mpi [no tcp check]

tcp hangs:
- test_worker_sim_dirs.py:# TESTSUITE_COMMS: mpi local
- test_persistent_aposmm_exception.py:# TESTSUITE_COMMS: local mpi

local passed - tcp got 'key error':
- test_aposmm_with_gradients.py:# TESTSUITE_COMMS: mpi

For those in the last two groups, I want to check whats happening for tcp issues.
Some of the aposmm tests previously did not work on local due to the PETSc issue. 

I want to extend the test comms where possible.

**Comment by jmlarson1** [comment] 2020-03-26 12:32
I moved the test `test_persistent_aposmm_periodic` to the second group as it has multiple calls.  

I agree with extending tests. Note that we are getting close to our 50 minute job limit on Travis.

**Comment by shuds13** [comment] 2020-03-26 13:36
Ok, thats a problem. One answer may be to separate mpi/local/tcp into different jobs.

**Comment by jlnav** [comment] 2020-03-26 14:51
``test_worker_sim_dirs.py`` also has multiple calls. Since this is just to test different configurations of libE_specs settings, i could split it up into two tests.

**Comment by jmlarson1** [comment] 2020-03-26 14:53
I wouldn't split yet.

**Comment by shuds13** [comment] 2020-03-26 15:06
> `test_worker_sim_dirs.py` also has multiple calls. Since this is just to test different configurations of libE_specs settings, I could split it up into two tests.

We probably want to test this with tcp, so probably make two tests.

**Comment by shuds13** [comment] 2020-03-26 15:09
> I wouldn't split yet.

We will try it out and see if fits in a job, but another advantage of splitting is it will be a quicker turn around anyway. Is there a good reason not to?

**Comment by jmlarson1** [comment] 2020-03-26 15:15
> I could split it up into two tests.

Sounds great. Please split into two so we can test with `tcp`. If possible, name the tests to distinguish between what is tested.

**Comment by jlnav** [comment] 2020-03-26 15:18
Alright. If we separate comms types into different jobs, would we then have twelve jobs running on travis for each PR/push? MPI/local/TCP for each Python version + macOS. It's a lot of jobs, but they'll all complete faster and we'll know immediately if a test failure is comms-specific.

**Comment by shuds13** [comment] 2020-03-26 15:19
Correct, I think the limit is 200 jobs.

**Comment by jlnav** [comment] 2020-05-28 17:56
Has this been accomplished as of the latest release? Jobs on Travis have been split up by comms type, and PRs adding comms types to several regression tests were merged.

**Comment by jmlarson1** [comment] 2020-05-28 19:42
Yes, this was resolved by #454

**Closed by jmlarson1** 2020-05-28 19:42 UTC
Labels: Testing

**Comment by shuds13** [comment] 2020-06-02 20:27
Actually in #454 I separated out the comms, but I didn't change for each test so I may want to re-check this. Unless @jmlarson1 did you add comms modes to the tests?
