### ISSUE TITLE
Option for not creating `ensemble` directory

### ISSUE THREAD

**Issue by AngelFP** [Libensemble/libensemble#974] opened 2023-01-31 15:47 UTC
Sometimes, the function to evaluate or optimize does not write any output to file. In this case, creating an `ensemble` folder is not necessary. Could there be an option (e.g., in the `libE_specs`) to choose whether this folder should be created?

**Comment by shuds13** [comment] 2023-02-01 16:34
@AngelFP Somewhere you have some `libE_specs` output options as in https://libensemble.readthedocs.io/en/main/history_output_logging.html#working-directories-for-user-functions - maybe `sim_dirs_make`. If none of these are set, then no `ensemble` directory is created. But you may want some way to separate input files/scripts?

**Comment by shuds13** [comment] 2023-02-01 17:20
Alternatively, if you set `use_worker_dirs` to True and `sim_dirs_make` to False, I think you would get the ensemble dir with just worker dirs inside. That way concurrent runs on workers is separated, but it won't keep input/output from every simulation - it will overwrite on each worker.

**Comment by AngelFP** [comment] 2023-02-17 15:37
Thanks! I'll play around with these options and see if that's all I would need.

**Comment by jlnav** [comment] 2023-04-17 16:57
Hi @AngelFP , has this been resolved? I believe at the time it should've been a small adjustment to your libE_specs to not produce an ensemble directory.

**Comment by AngelFP** [comment] 2023-04-18 15:57
Sure, these are the contents of the `libe_specs` I'm passing to the `libE` method: `{'sim_dirs_make': False, 'gen_dirs_make': False, 'save_every_k_sims': 2, 'dedicated_mode': False, 'comms': 'local', 'nworkers': 3}`

**Comment by jlnav** [comment] 2023-04-18 18:54
Thanks for the data! I've reproduced the issue on `main`, but am unable to reproduce on our `develop` branch. This is good, and means that after our upcoming release, it _should_ already be fixed.

If you want to verify that the future state of libEnsemble will remain compatible, and you haven't already done so, you're more than welcome to try again using our develop branch:

```
git clone https://github.com/Libensemble/libensemble.git
cd libensemble; git checkout remotes/origin/develop
pip install -e .
```

Note that an additional dependency, `pydantic`, will be installed.

**Comment by AngelFP** [comment] 2023-04-18 20:43
Ahh, I see. Thanks for checking! Glad to see this will work in the upcoming release. 

From my side, feel free to close this issue.

**Closed** 2023-04-28 15:01 UTC
